In [1]:
import pandas as pd

df = pd.read_csv('trends.csv')

In [2]:
df.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [3]:
df.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [4]:
df.shape

(26955, 5)

In [5]:
df.columns

Index(['location', 'year', 'category', 'rank', 'query'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  str
 1   year      26955 non-null  int64
 2   category  26955 non-null  str
 3   rank      26955 non-null  int64
 4   query     26955 non-null  str
dtypes: int64(2), str(3)
memory usage: 1.0 MB

In [7]:
df.dtypes

location      str
year        int64
category      str
rank        int64
query         str
dtype: object

In [8]:
df.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [9]:
df.describe(include='object')

/tmp/ipykernel_599/87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

             location category        query
count           26955    26955        26955
unique             83     2450        18431
top     United States   People  Paul Walker
freq             2070      760           84

In [10]:
df.nunique()

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [11]:
df['category'].unique()[:30]

<StringArray>
[            'Consumer Brands',                         'Men',
                      'Movies',          'MP3 Music Services',
                'Music Groups',                'New Products',
              'News Resources',                   'Retailers',
                      'Sports',                    'TV Shows',
                 'Video Games',                       'Women',
                    'Athletes',                'Kids' Images',
         'Musicians and Bands',                'News Stories',
                  'Technology',         'Travel Destinations',
                     'Marques',               'Personnalités',
        'Tendances de l'année', 'Die häufigsten Suchbegriffe',
   'Meist gesuchte Automarken', 'Meist gesuchte Musiker 2002',
                    'Searches',                'Anime Images',
         'Earthquake Searches',  'Fictional Character Images',
       'Male Celebrity Images',               'News Searches']
Length: 30, dtype: str

In [12]:
df.isnull().sum()

location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [13]:
(df.astype(str).apply(lambda col: col.str.strip().eq('')).sum())

location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(10)

In [15]:
df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head(20)

,location,year,category,rank,query
19995,Kazakhstan,2018,Жылдың фильмі/Фильм года,1,Веном
20000,Kazakhstan,2018,Жылдың фильмі/Фильм года,1,Веном
19996,Kazakhstan,2018,Жылдың фильмі/Фильм года,2,Мстители: Война бесконечности
20001,Kazakhstan,2018,Жылдың фильмі/Фильм года,2,Мстители: Война бесконечности
19997,Kazakhstan,2018,Жылдың фильмі/Фильм года,3,Бизнес по-казахски в Америке
20002,Kazakhstan,2018,Жылдың фильмі/Фильм года,3,Бизнес по-казахски в Америке
19998,Kazakhstan,2018,Жылдың фильмі/Фильм года,4,Монстры на каникулах 3
20003,Kazakhstan,2018,Жылдың фильмі/Фильм года,4,Монстры на каникулах 3
19999,Kazakhstan,2018,Жылдың фильмі/Фильм года,5,Дэдпул 2
20004,Kazakhstan,2018,Жылдың фильмі/Фильм года,5,Дэдпул 2
25395,Kenya,2020,Trending How To (Tech),1,How to fill Tpad online
25400,Kenya,2020,Trending How To (Tech),1,How to fill Tpad online
25396,Kenya,2020,Trending How To (Tech),2,How to create a website
25401,Kenya,2020,Trending How To (Tech),2,How to create a website
25397,Kenya,2020,Trending How To (Tech),3,How to connect a phone to TV
25402,Kenya,2020,Trending How To (Tech),3,How to connect a phone to TV
25398,Kenya,2020,Trending How To (Tech),4,How to make my electric plate cooker work
25403,Kenya,2020,Trending How To (Tech),4,How to make my electric plate cooker work
25399,Kenya,2020,Trending How To (Tech),5,How to take a screenshot on a laptop
25404,Kenya,2020,Trending How To (Tech),5,How to take a screenshot on a laptop